# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='fs-c.proto',
  package='de.pc2.dedup.fschunk',
  serialized_pb='\n\nfs-c.proto\x12\x14\x64\x65.pc2.dedup.fschunk\"\x1e\n\x08\x43hunkRun\x12\x12\n\nstart_date\x18\x01 \x02(\t\"o\n\x04\x46ile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x12\n\nchunkCount\x18\x04 \x01(\r\x12\r\n\x05label\x18\x05 \x01(\t\x12\x16\n\x07partial\x18\x06 \x01(\x08:\x05\x66\x61lse\"!\n\x05\x43hunk\x12\n\n\x02\x66p\x18\x02 \x01(\x0c\x12\x0c\n\x04size\x18\x03 \x01(\rB\nB\x08Protocol')




_CHUNKRUN = descriptor.Descriptor(
  name='ChunkRun',
  full_name='de.pc2.dedup.fschunk.ChunkRun',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='start_date', full_name='de.pc2.dedup.fschunk.ChunkRun.start_date', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=66,
)


_FILE = descriptor.Descriptor(
  name='File',
  full_name='de.pc2.dedup.fschunk.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='filename', full_name='de.pc2.dedup.fschunk.File.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='size', full_name='de.pc2.dedup.fschunk.File.size', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='de.pc2.dedup.fschunk.File.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='chunkCount', full_name='de.pc2.dedup.fschunk.File.chunkCount', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='label', full_name='de.pc2.dedup.fschunk.File.label', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='partial', full_name='de.pc2.dedup.fschunk.File.partial', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=68,
  serialized_end=179,
)


_CHUNK = descriptor.Descriptor(
  name='Chunk',
  full_name='de.pc2.dedup.fschunk.Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='fp', full_name='de.pc2.dedup.fschunk.Chunk.fp', index=0,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='size', full_name='de.pc2.dedup.fschunk.Chunk.size', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=181,
  serialized_end=214,
)

DESCRIPTOR.message_types_by_name['ChunkRun'] = _CHUNKRUN
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK

class ChunkRun(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHUNKRUN
  
  # @@protoc_insertion_point(class_scope:de.pc2.dedup.fschunk.ChunkRun)

class File(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FILE
  
  # @@protoc_insertion_point(class_scope:de.pc2.dedup.fschunk.File)

class Chunk(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHUNK
  
  # @@protoc_insertion_point(class_scope:de.pc2.dedup.fschunk.Chunk)

# @@protoc_insertion_point(module_scope)
